title = "Dvan"
description = "Config-free to build your Vue App"
contentLoading = true
host = "192.168.31.178"

[themeConfig]
repo = "dvanjs/dvan"
repoLabel = "GitHub"
docsRepo = "dvanjs/docsite"
docsDir = "docs"
editLinks = true
lastUpdated = true
displayAllHeaders = true

  [[themeConfig.nav]]
  text = "Guide"
  link = "/guide/introduction"

  [[themeConfig.nav]]
  text = "Config"
  link = "/config/"

  [[themeConfig.nav]]
  text = "Plugins"
  link = "/plugins/"

  [[themeConfig.nav]]
  text = "Versions"

    [[themeConfig.nav.items]]
    text = "v1.3.x"
    link = "https://v1.3.x--dvan.evila.me"

  [[themeConfig.sidebar]]
  title = "Basic"
  collapsable = false
  children = [
    "/guide/introduction",
    "/guide/quick-started",
    "/guide/configuration",
    "/guide/directory-structure"
  ]

  [[themeConfig.sidebar]]
  title = "Advanced"
  collapsable = false
  children = [
    "/guide/advanced/jsx"
  ]